# Site settings
title: Hapax legomenon
name: Christian Caballero # your name
email:
description: > # this means to ignore newlines until "baseurl:"
  Personal blog about AI, machine learning, linguistics, causal inference,
  and cognitive science.
baseurl: "/Nice_Blog" # the subpath of your site, e.g. /blog
url: "https://ccaballeroh.github.io" # the base hostname & protocol for your site
twitter_username: ccaballeroh10 # your Twitter username
github_username: ccaballeroh # your Github username

skillstree: false # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
